#ifndef ERP_COMPLAINS_GLOBAL_H
#define ERP_COMPLAINS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ERP_COMPLAINS_LIBRARY)
#  define ERP_COMPLAINSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ERP_COMPLAINSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ERP_COMPLAINS_GLOBAL_H
