#ifndef REPORTMASTER_GLOBAL_H
#define REPORTMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPORTMASTER_LIBRARY)
#  define REPORTMASTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REPORTMASTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REPORTMASTER_GLOBAL_H
