#ifndef UPDATESERVICE_GLOBAL_H
#define UPDATESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPDATESERVICE_LIBRARY)
#  define UPDATESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPDATESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPDATESERVICE_GLOBAL_H
