#ifndef MYSQLEMBEDDEDDRIVER_GLOBAL_H
#define MYSQLEMBEDDEDDRIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYSQLEMBEDDEDDRIVER_LIBRARY)
#  define MYSQLEMBEDDEDDRIVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYSQLEMBEDDEDDRIVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYSQLEMBEDDEDDRIVER_GLOBAL_H
