#ifndef ERP_PRODUCTION_GLOBAL_H
#define ERP_PRODUCTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ERP_PRODUCTION_LIBRARY)
#  define ERP_PRODUCTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ERP_PRODUCTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ERP_PRODUCTION_GLOBAL_H
