#ifndef CUSTOM_WIDGETS_GLOBAL_H
#define CUSTOM_WIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUSTOM_WIDGETS_LIBRARY)
#  define CUSTOM_WIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUSTOM_WIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUSTOM_WIDGETS_GLOBAL_H
