#ifndef DATAPUBLICS_GLOBAL_H
#define DATAPUBLICS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAPUBLICS_LIBRARY)
#  define DATAPUBLICSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAPUBLICSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAPUBLICS_GLOBAL_H
